"""second Migration

Revision ID: f31dd5cdc81d
Revises: 9ddfa69e150c
Create Date: 2019-02-18 19:34:29.663641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31dd5cdc81d'
down_revision = '9ddfa69e150c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subscribers_pkey'),
    sa.UniqueConstraint('email', name='subscribers_email_key')
    )
    # ### end Alembic commands ###
