"""Fifth Migration

Revision ID: fe650d310144
Revises: 2afc70706e57
Create Date: 2019-02-19 11:20:22.773605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe650d310144'
down_revision = '2afc70706e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('description', sa.String(length=1000), nullable=True))
    op.drop_constraint('comments_blog_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blog_fkey', 'comments', 'blogs', ['blog'], ['id'])
    op.drop_column('comments', 'description')
    op.drop_column('comments', 'blog_id')
    # ### end Alembic commands ###
